# properties > yml : 불필요한 반복 코드 삭제 / 가독성 확보(계층 구조)
server:
  port: 8001
  error:
    include-exception: true
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    whitelabel:
      enabled: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thekhanhwa?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: thekmanager
    password: thek1234
  mvc:
    converters:
      preferred-json-mapper: gson
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
    pathmatch:
      matching-strategy: ant_path_matcher
